# Generated by Django 2.1.5 on 2020-10-14 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=250, unique_for_date="publish", verbose_name="Слаг")),
                ("body", models.TextField(verbose_name="Текст")),
                ("publish", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Опубликованно")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Созданно")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("черновик", "Черновик"), ("опубликовано", "Опубликовано")], default="черновик", max_length=12, verbose_name="Статус")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blog_posts", to=settings.AUTH_USER_MODEL, verbose_name="Автор")),
            ],
            options={
                "ordering": ("-publish",),
            },
        ),
    ]
