# Generated by Django 2.1.5 on 2020-10-15 16:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-publish",), "verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
