# Generated by Django 2.1.5 on 2020-11-04 11:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_auto_20201024_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Текст"),
        ),
    ]
